# Generated by Django 5.1.6 on 2025-03-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_representative_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
