# Generated by Django 5.1.6 on 2025-03-01 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=100, unique=True)),
                ('product_title', models.CharField(max_length=200)),
                ('rim_quantity', models.IntegerField(default=0)),
                ('sheet_quantity', models.IntegerField(default=0)),
                ('only_sheet_piece', models.IntegerField(default=0)),
                ('total_sheet_piece', models.IntegerField(default=0)),
                ('rim_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sheet_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('previous_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('today_bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('today_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_by', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('order_date', models.DateField()),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('transport', models.CharField(choices=[('Company Transport', 'Company Transport'), ('Sharif Paper & Stationary Transport', 'Sharif Paper & Stationary Transport'), ('Other Transport', 'Other Transport')], max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('invoice_challan_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=100, unique=True)),
                ('godown_no', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_challan_date', models.DateField()),
                ('supplier', models.CharField(max_length=255)),
                ('kind_of_product', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('Local', 'Local'), ('Import', 'Import')], max_length=50)),
                ('product_entry_date', models.DateField()),
                ('remarks_1', models.TextField(blank=True, null=True)),
                ('remarks_2', models.TextField(blank=True, null=True)),
                ('name_of_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.item')),
            ],
        ),
    ]
