# Generated by Django 5.1.6 on 2025-03-04 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_no', models.CharField(max_length=100, unique=True)),
                ('invoice_challan_date', models.DateField()),
                ('invoice_challan_no', models.CharField(max_length=100, unique=True)),
                ('transport_type', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('delivery_no', models.CharField(max_length=100, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('previous_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice_challan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('today_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_type', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='master.company')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godwons', to='master.godown')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=255)),
                ('rim', models.IntegerField(default=0)),
                ('dozen', models.IntegerField(default=0)),
                ('sheet_or_piece', models.IntegerField(default=0)),
                ('only_sheet_piece', models.IntegerField(default=0)),
                ('total_sheet_piece', models.IntegerField(default=0)),
                ('rim_or_dozen_per_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sheet_or_piece_per_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('road_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_extra_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_per_rim_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_per_sheet_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rim_or_dozen_total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sheet_or_piece_total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rim_or_dozen_per_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rim_or_dozen_per_sell_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sheet_or_piece_per_sell_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.purchase')),
            ],
        ),
    ]
