# Generated by Django 5.1.6 on 2025-03-09 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_no', models.CharField(max_length=100, unique=True)),
                ('invoice_challan_date', models.DateField()),
                ('invoice_challan_no', models.CharField(max_length=100, unique=True)),
                ('transport_type', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('delivery_no', models.CharField(max_length=100, unique=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_by', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('previous_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice_challan_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('today_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_type', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='master.company')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godwons', to='master.godown')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rim', models.IntegerField(default=0)),
                ('dozen', models.IntegerField(default=0)),
                ('only_sheet_or_piece', models.IntegerField(default=0)),
                ('total_sheet_or_piece', models.IntegerField(default=0)),
                ('per_rim_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('per_dozen_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('per_sheet_or_piece_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('per_rim_sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_dozen_sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_sheet_or_piece_sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now_add=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('invoice_total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('today_paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_type', models.CharField(max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='master.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rim', models.IntegerField(default=0)),
                ('dozen', models.IntegerField(default=0)),
                ('sheet_or_piece', models.IntegerField(default=0)),
                ('last_per_rim_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_rim_total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_per_dozen_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_dozen_total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_per_sheet_or_piece_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_sheet_or_piece_total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.product')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rim_sold', models.IntegerField(default=0)),
                ('dozen_sold', models.IntegerField(default=0)),
                ('sheet_or_piece_sold', models.IntegerField(default=0)),
                ('per_rim_sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_dozen_sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('per_sheet_or_piece_sell_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Inventory.sale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.stock')),
            ],
        ),
    ]
