# Generated by Django 5.1.6 on 2025-03-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_purchase_company_alter_purchase_godown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
