# Generated by Django 5.1.6 on 2025-02-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('extra_field1', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_field2', models.CharField(blank=True, max_length=255, null=True)),
                ('extra_field3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
